createdb -U postgres MyHomework
psql -U postgres -d MyHomework

CREATE TABLE IF NOT NOT EXISTS Artist (
	Id SERIAL PRIMARY KEY,
	name VARCHAR (850) NOT NULL
	);

CREATE TABLE IF NOT EXISTS Genre (
	Id SERIAL PRIMARY KEY,
	name VARCHAR (850) NOT NULL
	);

CREATE TABLE IF NOT EXISTS Albums (
	Id SERIAL PRIMARY KEY,
	name VARCHAR (850) NOT NULL
	);



CREATE TABLE IF NOT EXISTS Collection
	Id SERIAL PRIMARY KEY,
	name VARCHAR (850) NOT NULL,
	year INTEGER NOT NULL CHECK(releaseyear>0)
	);


CREATE TABLE IF NOT EXISTS Artist_genre (
	ArtistID INTEGER REFERENCES Artist(Id),
	GenreID INTEGER REFERENCES Genre(Id),
	CONSTRAINT pkAG PRIMARY KEY (ArtistID, GenreID)
	);


CREATE TABLE IF NOT EXISTS Track (
	Id SERIAL PRIMARY KEY,
	AlbumID INTEGER NOT NULL REFERENCES Albums(Id),
	name VARCHAR (850) NOT NULL,
	time TIME NOT NULL
	);

CREATE TABLE IF NOT EXISTS Artist_albums (
	ArtistID INTEGER REFERENCES Artist(Id),
	AlbumID INTEGER REFERENCES Album(Id),
	CONSTRAINT pkAA PRIMARY KEY (ArtistID, AlbumID)
	);



CREATE TABLE IF NOT EXISTS Collection_list (
	TrackID INTEGER REFERENCES Track(Id),
	CollID INTEGER REFERENCES Collection(Id),
	CONSTRAINT pkCL PRIMARY KEY TrackID, CollID)
	);
